ExperienceTracker/Models/Player.cs
using System.Collections.Generic;

namespace ExperienceTracker.Models
{
    public class Player : BaseModel
    {
        public Player()
        {
            Characters = new HashSet<Character>();
            Campaigns = new HashSet<CampaignPlayer>();
        }

        public string Name { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<CampaignPlayer> Campaigns { get; set; }
    }
}

ExperienceTracker/Controllers/CampaignPlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExperienceTracker.Models;

namespace ExperienceTracker.Controllers
{
    public class CampaignPlayersController : Controller
    {
        private readonly ExperienceTrackerContext _context;

        public CampaignPlayersController(ExperienceTrackerContext context)
        {
            _context = context;
        }

        // GET: CampaignPlayers
        public async Task<IActionResult> Index()
        {
            var experienceTrackerContext = _context.CampaignPlayer.Include(c => c.Campaign).Include(c => c.Player);
            return View(await experienceTrackerContext.ToListAsync());
        }

        // GET: CampaignPlayers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var campaignPlayer = await _context.CampaignPlayer
                .Include(c => c.Campaign)
                .Include(c => c.Player)
                .FirstOrDefaultAsync(m => m.PlayerId == id);
            if (campaignPlayer == null)
            {
                return NotFound();
            }

            return View(campaignPlayer);
        }

        // GET: CampaignPlayers/Create
        public IActionResult Create()
        {
            ViewData["CampaignId"] = new SelectList(_context.Campaigns, "Id", "Id");
            ViewData["PlayerId"] = new SelectList(_context.Players, "Id", "Id");
            return View();
        }

        // POST: CampaignPlayers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerId,CampaignId")] CampaignPlayer campaignPlayer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(campaignPlayer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CampaignId"] = new SelectList(_context.Campaigns, "Id", "Id", campaignPlayer.CampaignId);
            ViewData["PlayerId"] = new SelectList(_context.Players, "Id", "Id", campaignPlayer.PlayerId);
            return View(campaignPlayer);
        }

        // GET: CampaignPlayers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var campaignPlayer = await _context.CampaignPlayer.FindAsync(id);
            if (campaignPlayer == null)
            {
                return NotFound();
            }
            ViewData["CampaignId"] = new SelectList(_context.Campaigns, "Id", "Id", campaignPlayer.CampaignId);
            ViewData["PlayerId"] = new SelectList(_context.Players, "Id", "Id", campaignPlayer.PlayerId);
            return View(campaignPlayer);
        }

        // POST: CampaignPlayers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlayerId,CampaignId")] CampaignPlayer campaignPlayer)
        {
            if (id != campaignPlayer.PlayerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(campaignPlayer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CampaignPlayerExists(campaignPlayer.PlayerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CampaignId"] = new SelectList(_context.Campaigns, "Id", "Id", campaignPlayer.CampaignId);
            ViewData["PlayerId"] = new SelectList(_context.Players, "Id", "Id", campaignPlayer.PlayerId);
            return View(campaignPlayer);
        }

        // GET: CampaignPlayers/Delete/5
        [HttpGet]
        [Route("Campaigns/{campaignId}/Players/{playerId}/")]
        public async Task<IActionResult> Delete(int? campaignId, int? playerId)
        {
            if (campaignId == null || playerId == null)
            {
                return NotFound();
            }

            var campaignPlayer = await _context.CampaignPlayer
                .Include(c => c.Campaign)
                .Include(c => c.Player)
                .FirstOrDefaultAsync(m => m.PlayerId == playerId && m.CampaignId == campaignId);
            if (campaignPlayer == null)
            {
                return NotFound();
            }

            return View(campaignPlayer);
        }

        // POST: CampaignPlayers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int campaignId, int playerId)
        {
            var campaignPlayer = await _context.CampaignPlayer.FindAsync(campaignId, playerId);
            _context.CampaignPlayer.Remove(campaignPlayer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CampaignPlayerExists(int id)
        {
            return _context.CampaignPlayer.Any(e => e.PlayerId == id);
        }
    }
}

ExperienceTracker/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExperienceTracker.Models;

namespace ExperienceTracker.Controllers
{
    public class PlayersController : Controller
    {
        private readonly ExperienceTrackerContext _context;

        public PlayersController(ExperienceTrackerContext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            return View(await _context.Players.ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .Include(p => p.Campaigns)
                .ThenInclude(pc => pc.Campaign)
                .ThenInclude(c => c.Characters)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] Player player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Players.FindAsync(id);
            _context.Players.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Players.Any(e => e.Id == id);
        }
    }
}

ExperienceTracker/Views/Players/Create.cshtml
@model ExperienceTracker.Models.Player

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExperienceTracker/Views/Players/Delete.cshtml
@model ExperienceTracker.Models.Player

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExperienceTracker/Views/Players/Details.cshtml
@model ExperienceTracker.Models.Player

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Campaigns)
        </dt>
        <dd>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayName("Character")
                        </th>
                        <th>
                            @Html.DisplayName("Experience")
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Campaigns)
                    {
                        var characters = item.Campaign.Characters.Where(c => c.PlayerId == Model.Id);
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Campaign.Name)
                            </td>
                            @if (characters.Count() > 0)
                            {
                                <td>
                                    <table>
                                        <tbody>
                                            @foreach (var character in characters)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => character.Name)
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </td>
                                <td>
                                    <table>
                                        <tbody>
                                            @foreach (var character in characters)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => character.Experience)
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </td>
                            }
                            else
                            {
                                <td>
                                    @Html.DisplayName("Not Available")
                                </td>
                                <td>
                                    @Html.DisplayName("Not Available")
                                </td>
                            }
                            <td>
                                <a asp-controller="Players" asp-action="Edit" asp-route-id="@item.CampaignId">Edit</a> |
                                <a asp-controller="Players" asp-action="Details" asp-route-id="@item.CampaignId">Details</a> |
                                <a asp-controller="CampaignPlayers" asp-action="Delete" asp-all-route-data="@{new Dictionary<string, string> { {"campaignId", item.CampaignId.ToString() }, { "playerId", item.Player.Id.ToString() } }}">Remove</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ExperienceTracker/Views/Players/Edit.cshtml
@model ExperienceTracker.Models.Player

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExperienceTracker/Views/Players/Index.cshtml
@model IEnumerable<ExperienceTracker.Models.Player>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>